[package]
name = "fzfx"
version = "0.1.0"
edition = "2024"
authors = ["Amartya Chowdhury"]
description = "Fast, semantic CLI command finder powered by local embeddings."
readme = "README.md"
license = "MIT"
homepage = "https://github.com/aether-flux/fzfx"
repository = "https://github.com/aether-flux/fzfx"
keywords = ["cli", "fuzzy", "semantic", "finder", "onnx"]
categories = ["command-line-utilities"]

[dependencies]
ahash = "0.8.12"
anyhow = "1.0.104"
arboard = { version = "3.6.1", features = ["wayland-data-control"] }
bincode = "1.3.3"
clap = { version = "4.6.7", features = ["derive"] }
dirs = "7.0.0"
fastembed = "7.1.0"
inquire = "0.9.4"
serde = { version = "1.0.229", features = ["derive"] }
